AWSTemplateFormatVersion: '2010-09-09'

Resources:

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: grafana-alert-topic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: rasikabhandari2@gmail.com
      TopicArn: !Ref SNSTopic